sonar.projectKey=GitHubActionsDemo
sonar.working.directory=D:\\Subu\\GitHubActionsDemo\\GitHubActionsDemo\\.sonarqube\\out\\.sonar
sonar.projectBaseDir=D:\\Subu\\GitHubActionsDemo\\GitHubActionsDemo
sonar.pullrequest.cache.basepath=D:\\Subu\\GitHubActionsDemo\\GitHubActionsDemo

BC736628-76CA-4726-BEB4-BAD3B425BBA6.sonar.projectKey=GitHubActionsDemo:BC736628-76CA-4726-BEB4-BAD3B425BBA6
BC736628-76CA-4726-BEB4-BAD3B425BBA6.sonar.projectName=GitHubActionsDemo
BC736628-76CA-4726-BEB4-BAD3B425BBA6.sonar.projectBaseDir=D:\\Subu\\GitHubActionsDemo\\GitHubActionsDemo
BC736628-76CA-4726-BEB4-BAD3B425BBA6.sonar.sourceEncoding=utf-8
BC736628-76CA-4726-BEB4-BAD3B425BBA6.sonar.tests=
BC736628-76CA-4726-BEB4-BAD3B425BBA6.sonar.sources=\
"D:\\Subu\\GitHubActionsDemo\\GitHubActionsDemo\\Program.cs",\
"D:\\Subu\\GitHubActionsDemo\\GitHubActionsDemo\\obj\\Debug\\net10.0\\GitHubActionsDemo.GlobalUsings.g.cs",\
"D:\\Subu\\GitHubActionsDemo\\GitHubActionsDemo\\obj\\Debug\\net10.0\\.NETCoreApp,Version=v10.0.AssemblyAttributes.cs",\
"D:\\Subu\\GitHubActionsDemo\\GitHubActionsDemo\\obj\\Debug\\net10.0\\GitHubActionsDemo.AssemblyInfo.cs",\
"D:\\Subu\\GitHubActionsDemo\\GitHubActionsDemo\\obj\\Debug\\net10.0\\GitHubActionsDemo.MvcApplicationPartsAssemblyInfo.cs",\
"D:\\Subu\\GitHubActionsDemo\\GitHubActionsDemo\\appsettings.Development.json",\
"D:\\Subu\\GitHubActionsDemo\\GitHubActionsDemo\\appsettings.json",\
"D:\\Subu\\GitHubActionsDemo\\GitHubActionsDemo\\GitHubActionsDemo.http",\
"D:\\Subu\\GitHubActionsDemo\\GitHubActionsDemo\\Properties\\launchSettings.json",\
"D:\\Subu\\GitHubActionsDemo\\GitHubActionsDemo\\obj\\GitHubActionsDemo.csproj.nuget.dgspec.json",\
"D:\\Subu\\GitHubActionsDemo\\GitHubActionsDemo\\obj\\project.assets.json",\
"D:\\Subu\\GitHubActionsDemo\\GitHubActionsDemo\\.github\\workflows\\build.yml",\
"D:\\Subu\\GitHubActionsDemo\\GitHubActionsDemo\\bin\\Debug\\net10.0\\appsettings.Development.json",\
"D:\\Subu\\GitHubActionsDemo\\GitHubActionsDemo\\bin\\Debug\\net10.0\\appsettings.json",\
"D:\\Subu\\GitHubActionsDemo\\GitHubActionsDemo\\bin\\Debug\\net10.0\\GitHubActionsDemo.deps.json",\
"D:\\Subu\\GitHubActionsDemo\\GitHubActionsDemo\\bin\\Debug\\net10.0\\GitHubActionsDemo.runtimeconfig.json",\
"D:\\Subu\\GitHubActionsDemo\\GitHubActionsDemo\\bin\\Debug\\net10.0\\GitHubActionsDemo.staticwebassets.endpoints.json",\
"D:\\Subu\\GitHubActionsDemo\\GitHubActionsDemo\\obj\\Debug\\net10.0\\GitHubActionsDemo.sourcelink.json",\
"D:\\Subu\\GitHubActionsDemo\\GitHubActionsDemo\\obj\\Debug\\net10.0\\rjsmcshtml.dswa.cache.json",\
"D:\\Subu\\GitHubActionsDemo\\GitHubActionsDemo\\obj\\Debug\\net10.0\\rjsmrazor.dswa.cache.json",\
"D:\\Subu\\GitHubActionsDemo\\GitHubActionsDemo\\obj\\Debug\\net10.0\\rpswa.dswa.cache.json",\
"D:\\Subu\\GitHubActionsDemo\\GitHubActionsDemo\\obj\\Debug\\net10.0\\staticwebassets.build.endpoints.json",\
"D:\\Subu\\GitHubActionsDemo\\GitHubActionsDemo\\obj\\Debug\\net10.0\\staticwebassets.build.json"

BC736628-76CA-4726-BEB4-BAD3B425BBA6.sonar.cs.analyzer.projectOutPaths=\
"D:\\Subu\\GitHubActionsDemo\\GitHubActionsDemo\\.sonarqube\\out\\0"
BC736628-76CA-4726-BEB4-BAD3B425BBA6.sonar.cs.roslyn.reportFilePaths=\
"D:\\Subu\\GitHubActionsDemo\\GitHubActionsDemo\\.sonarqube\\out\\0\\Issues.json"
BC736628-76CA-4726-BEB4-BAD3B425BBA6.sonar.cs.scanner.telemetry=\
"D:\\Subu\\GitHubActionsDemo\\GitHubActionsDemo\\.sonarqube\\out\\0\\Telemetry.json"

BC736628-76CA-4726-BEB4-BAD3B425BBA6.sonar.working.directory=D:\\Subu\\GitHubActionsDemo\\GitHubActionsDemo\\.sonarqube\\out\\.sonar\\mod0
sonar.host.url=http://localhost:9000
sonar.visualstudio.enable=false

sonar.modules=BC736628-76CA-4726-BEB4-BAD3B425BBA6

